export const sectionTitles: string[] = [
  "Title",
  "Abstract.",
  "1.Introduction",
  "2.Transactions",
  "3.Timestamp Server",
  "4.Proof-of-Work",
  "5.Network",
  "6.Incentive",
  "7.Reclaiming Disk Space",
  "8.Simplified Payment Verification",
  "9.Combining and Splitting Value",
  "10.Privacy",
  "11.Calculations",
  "12.Conclusion",
  "References",
];
